# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='jb.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bunk',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='jb.UserProfile'),
        ),
    ]
